#!/bin/ash

#TODO: self upgrade
`echo 1 > /sys/devices/platform/leds/leds/c20-v1:blue:wan/brightness`
`echo 1 > /sys/devices/platform/leds/leds/c20-v1:orange:wan/brightness`
sleep 1
echo "$ACTION"
echo "$INTERFACE"
if ["${ACTION}"=="ifup" & "${INTERFACE}" == "wan"] ; then
	echo "check"
	IP=$(ip addr show pppoe-wan | grep -o 'inet [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' | grep -o [0-9].*)
	icanhazip=`wget -q -4 -O- http://icanhazip.com`
	echo $IP
	echo $icanhazip
	if [ "$IP" == "$icanhazip" ] ; then
		echo "Not NAT"
		`echo 0 > /sys/devices/platform/leds/leds/c20-v1:blue:wan/brightness`
		`echo 0 > /sys/devices/platform/leds/leds/c20-v1:orange:wan/brightness`
		echo "Done"
		echo "Keep calm and enjoy"
	else
		echo "Is NAT"
		
		#reboot pppoe
		echo "wan restarting"
		`/sbin/ifup wan`
	fi
fi
